# Generated by Django 5.2.4 on 2025-07-31 10:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_dailysalesreport_feedbackrequest_customerfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbackrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='business',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='daily_report',
        ),
        migrations.RemoveField(
            model_name='review',
            name='business_response',
        ),
        migrations.AddField(
            model_name='review',
            name='auto_publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='communication_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Customer service, responsiveness', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_auto_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='logistics_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Shipping, delivery, packaging', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='negative_comment',
            field=models.TextField(blank=True, help_text='Detailed explanation for negative feedback'),
        ),
        migrations.AddField(
            model_name='review',
            name='positive_comment',
            field=models.TextField(blank=True, help_text='Additional positive feedback'),
        ),
        migrations.AddField(
            model_name='review',
            name='store_response',
            field=models.TextField(blank=True, help_text='Store response to review'),
        ),
        migrations.AddField(
            model_name='review',
            name='website_usability_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Website experience, ease of ordering', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='General review comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.order'),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_moderation', 'Pending Moderation'), ('published', 'Published'), ('disputed', 'Under Dispute'), ('auto_published', 'Auto Published (7 days)'), ('hidden', 'Hidden by Store'), ('appealed', 'Appealed'), ('archived', 'Archived')], default='pending_moderation', max_length=20),
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('email_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('responded', 'Response Received'), ('expired', 'Expired (7 days)'), ('invalid', 'Invalid Email/Customer')], default='pending', max_length=20)),
                ('email_sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='reviews.business')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='reviews.dailysalesreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'order_id', 'customer_email')},
            },
        ),
        migrations.AddField(
            model_name='review',
            name='review_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.reviewrequest'),
        ),
        migrations.DeleteModel(
            name='CustomerFeedback',
        ),
        migrations.DeleteModel(
            name='FeedbackRequest',
        ),
    ]
