# Generated by Django 5.2.4 on 2025-07-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_feedbackrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='auto_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='product_name',
            field=models.CharField(blank=True, help_text='Product or service name', max_length=200),
        ),
    ]
